//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomlet.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeliberatelyIncorrectTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliberatelyIncorrectTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tomlet.Tests.DeliberatelyIncorrectTestResources", typeof(DeliberatelyIncorrectTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [fruit.physical]  # subtable, but to which parent element should it belong?
        ///color = &quot;red&quot;
        ///shape = &quot;round&quot;
        ///
        ///[[fruit]]  # parser must throw an error upon discovering that &quot;fruit&quot; is
        ///           # an array rather than a table
        ///name = &quot;apple&quot;.
        /// </summary>
        internal static string DefiningAsArrayWhenAlreadyTableTestInput {
            get {
                return ResourceManager.GetString("DefiningAsArrayWhenAlreadyTableTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type = { name = &quot;Nail&quot; }
        ///type.edible = false  # INVALID.
        /// </summary>
        internal static string InlineTableLockedTestInput {
            get {
                return ResourceManager.GetString("InlineTableLockedTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [fruit]
        ///apple = &quot;red&quot;
        ///
        ///[fruit.apple]
        ///texture = &quot;smooth&quot;.
        /// </summary>
        internal static string KeyRedefinitionViaTableTestInput {
            get {
                return ResourceManager.GetString("KeyRedefinitionViaTableTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # INVALID TOML DOC
        ///fruits = []
        ///
        ///[[fruits]] # Not allowed.
        /// </summary>
        internal static string ReDefiningAnArrayAsATableArrayIsAnErrorTestInput {
            get {
                return ResourceManager.GetString("ReDefiningAnArrayAsATableArrayIsAnErrorTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # INVALID TOML DOC
        ///[[fruits]]
        ///name = &quot;apple&quot;
        ///
        ///[[fruits.varieties]]
        ///name = &quot;red delicious&quot;
        ///
        ///# INVALID: This table conflicts with the previous array of tables
        ///[fruits.varieties]
        ///name = &quot;granny smith&quot;
        ///
        ///[fruits.physical]
        ///color = &quot;red&quot;
        ///shape = &quot;round&quot;
        ///
        ///# INVALID: This array of tables conflicts with the previous table
        ///[[fruits.physical]]
        ///color = &quot;green&quot;.
        /// </summary>
        internal static string ReDefiningSubTableAsSubTableArrayTestInput {
            get {
                return ResourceManager.GetString("ReDefiningSubTableAsSubTableArrayTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [fruit]
        ///apple = &quot;red&quot;
        ///
        ///[fruit]
        ///orange = &quot;orange&quot;.
        /// </summary>
        internal static string TableRedefinitionTestInput {
            get {
                return ResourceManager.GetString("TableRedefinitionTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myArr = [1, 2, 3}.
        /// </summary>
        internal static string TomlBadArrayExample {
            get {
                return ResourceManager.GetString("TomlBadArrayExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date = 2021-13-13T08:30:00.
        /// </summary>
        internal static string TomlBadDateExample {
            get {
                return ResourceManager.GetString("TomlBadDateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array = [1,2,3]
        ///[array.a]
        ///value = 1.
        /// </summary>
        internal static string TomlBadDottedKeyExample {
            get {
                return ResourceManager.GetString("TomlBadDottedKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum = &quot;QUX&quot;.
        /// </summary>
        internal static string TomlBadEnumExample {
            get {
                return ResourceManager.GetString("TomlBadEnumExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid = &quot;hello\z&quot;.
        /// </summary>
        internal static string TomlBadEscapeExample {
            get {
                return ResourceManager.GetString("TomlBadEscapeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point = { x = 1, y  2 }.
        /// </summary>
        internal static string TomlBadInlineTableExample {
            get {
                return ResourceManager.GetString("TomlBadInlineTableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number = 1.e3.
        /// </summary>
        internal static string TomlBadNumberExample {
            get {
                return ResourceManager.GetString("TomlBadNumberExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &quot;&quot;hello, world&quot;&quot;.
        /// </summary>
        internal static string TomlBadStringExample {
            get {
                return ResourceManager.GetString("TomlBadStringExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badDate = 2021-05-0512:00:00.
        /// </summary>
        internal static string TomlDateTimeWithNoSeparatorExample {
            get {
                return ResourceManager.GetString("TomlDateTimeWithNoSeparatorExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myTable..badKey = &quot;hello&quot;.
        /// </summary>
        internal static string TomlDoubleDottedKeyExample {
            get {
                return ResourceManager.GetString("TomlDoubleDottedKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = {a = &quot;one&quot; b = &quot;two&quot;}.
        /// </summary>
        internal static string TomlInlineTableWithMissingSeparatorExample {
            get {
                return ResourceManager.GetString("TomlInlineTableWithMissingSeparatorExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = {a = 1, b = 2,
        ///c = 3}.
        /// </summary>
        internal static string TomlInlineTableWithNewlineExample {
            get {
                return ResourceManager.GetString("TomlInlineTableWithNewlineExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badTime = 07:00:00Z.
        /// </summary>
        internal static string TomlLocalTimeWithOffsetExample {
            get {
                return ResourceManager.GetString("TomlLocalTimeWithOffsetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;key&quot; 1.
        /// </summary>
        internal static string TomlMissingEqualsExample {
            get {
                return ResourceManager.GetString("TomlMissingEqualsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = &quot;a&quot;.
        /// </summary>
        internal static string TomlMissingKeyExample {
            get {
                return ResourceManager.GetString("TomlMissingKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TomlNullBytesExample {
            get {
                return ResourceManager.GetString("TomlNullBytesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[numbers.one]]
        ///value = 1.
        /// </summary>
        internal static string TomlTableArrayWithMissingIntermediateExample {
            get {
                return ResourceManager.GetString("TomlTableArrayWithMissingIntermediateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &quot;&quot;&quot;literally three quotes: &quot;&quot;&quot;&quot;&quot;&quot;.
        /// </summary>
        internal static string TomlTripleDoubleQuoteInStringExample {
            get {
                return ResourceManager.GetString("TomlTripleDoubleQuoteInStringExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;&quot;key&quot;&quot;&quot; = 1.
        /// </summary>
        internal static string TomlTripleQuotedKeyExample {
            get {
                return ResourceManager.GetString("TomlTripleQuotedKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &apos;&apos;&apos;literally three quotes: &apos;&apos;&apos;&apos;&apos;&apos;.
        /// </summary>
        internal static string TomlTripleSingleQuoteInStringExample {
            get {
                return ResourceManager.GetString("TomlTripleSingleQuoteInStringExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string =.
        /// </summary>
        internal static string TomlTruncatedFileExample {
            get {
                return ResourceManager.GetString("TomlTruncatedFileExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string TomlTruncatedFileExample2 {
            get {
                return ResourceManager.GetString("TomlTruncatedFileExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string TomlTruncatedFileExample3 {
            get {
                return ResourceManager.GetString("TomlTruncatedFileExample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badDate = 2021-05-05T.
        /// </summary>
        internal static string TomlUnnecessaryDateTimeSeparatorExample {
            get {
                return ResourceManager.GetString("TomlUnnecessaryDateTimeSeparatorExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arr = [1, 2
        ///anotherKey = &quot;hello&quot;.
        /// </summary>
        internal static string TomlUnterminatedArrayExample {
            get {
                return ResourceManager.GetString("TomlUnterminatedArrayExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;key = 1.
        /// </summary>
        internal static string TomlUnterminatedQuotedKeyExample {
            get {
                return ResourceManager.GetString("TomlUnterminatedQuotedKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &quot;one.
        /// </summary>
        internal static string TomlUnterminatedStringExample {
            get {
                return ResourceManager.GetString("TomlUnterminatedStringExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[array
        ///one = 1.
        /// </summary>
        internal static string TomlUnterminatedTableArrayExample {
            get {
                return ResourceManager.GetString("TomlUnterminatedTableArrayExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [table
        ///one = 1.
        /// </summary>
        internal static string TomlUnterminatedTableExample {
            get {
                return ResourceManager.GetString("TomlUnterminatedTableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key name = 1.
        /// </summary>
        internal static string TomlWhitespaceInKeyExample {
            get {
                return ResourceManager.GetString("TomlWhitespaceInKeyExample", resourceCulture);
            }
        }
    }
}
