//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomlet.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeliberatelyIncorrectTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliberatelyIncorrectTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tomlet.Tests.DeliberatelyIncorrectTestResources", typeof(DeliberatelyIncorrectTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myArr = [1, 2, 3}.
        /// </summary>
        internal static string TomlBadArrayExample {
            get {
                return ResourceManager.GetString("TomlBadArrayExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date = 2021-13-13T08:30:00.
        /// </summary>
        internal static string TomlBadDateExample {
            get {
                return ResourceManager.GetString("TomlBadDateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array = [1,2,3]
        ///[array.a]
        ///value = 1.
        /// </summary>
        internal static string TomlBadDottedKeyExample {
            get {
                return ResourceManager.GetString("TomlBadDottedKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum = &quot;QUX&quot;.
        /// </summary>
        internal static string TomlBadEnumExample {
            get {
                return ResourceManager.GetString("TomlBadEnumExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid = &quot;hello\z&quot;.
        /// </summary>
        internal static string TomlBadEscapeExample {
            get {
                return ResourceManager.GetString("TomlBadEscapeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point = { x = 1, y  2 }.
        /// </summary>
        internal static string TomlBadInlineTableExample {
            get {
                return ResourceManager.GetString("TomlBadInlineTableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number = 1.e3.
        /// </summary>
        internal static string TomlBadNumberExample {
            get {
                return ResourceManager.GetString("TomlBadNumberExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badDate = 2021-05-0512:00:00.
        /// </summary>
        internal static string TomlDateTimeWithNoSeparatorExample {
            get {
                return ResourceManager.GetString("TomlDateTimeWithNoSeparatorExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badTime = 07:00:00Z.
        /// </summary>
        internal static string TomlLocalTimeWithOffsetExample {
            get {
                return ResourceManager.GetString("TomlLocalTimeWithOffsetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = &quot;a&quot;.
        /// </summary>
        internal static string TomlMissingKeyExample {
            get {
                return ResourceManager.GetString("TomlMissingKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[numbers.one]]
        ///value = 1.
        /// </summary>
        internal static string TomlTableArrayWithMissingIntermediateExample {
            get {
                return ResourceManager.GetString("TomlTableArrayWithMissingIntermediateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string =.
        /// </summary>
        internal static string TomlTruncatedFileExample {
            get {
                return ResourceManager.GetString("TomlTruncatedFileExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badDate = 2021-05-05T.
        /// </summary>
        internal static string TomlUnnecessaryDateTimeSeparatorExample {
            get {
                return ResourceManager.GetString("TomlUnnecessaryDateTimeSeparatorExample", resourceCulture);
            }
        }
    }
}
