//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomlet.Tests {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeliberatelyIncorrectTestResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliberatelyIncorrectTestResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tomlet.Tests.DeliberatelyIncorrectTestResources", typeof(DeliberatelyIncorrectTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TomlBadInlineTableExample {
            get {
                return ResourceManager.GetString("TomlBadInlineTableExample", resourceCulture);
            }
        }
        
        internal static string TomlBadEscapeExample {
            get {
                return ResourceManager.GetString("TomlBadEscapeExample", resourceCulture);
            }
        }
        
        internal static string TomlBadNumberExample {
            get {
                return ResourceManager.GetString("TomlBadNumberExample", resourceCulture);
            }
        }
        
        internal static string TomlBadDateExample {
            get {
                return ResourceManager.GetString("TomlBadDateExample", resourceCulture);
            }
        }
        
        internal static string TomlTruncatedFileExample {
            get {
                return ResourceManager.GetString("TomlTruncatedFileExample", resourceCulture);
            }
        }
    }
}
