//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomlet.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tomlet.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &quot;value&quot;.
        /// </summary>
        internal static string BasicKVPTestInput {
            get {
                return ResourceManager.GetString("BasicKVPTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot; = &quot;blank&quot;     # VALID but discouraged.
        /// </summary>
        internal static string BlankKeysAreAcceptedTestInput {
            get {
                return ResourceManager.GetString("BlankKeysAreAcceptedTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This is a full-line comment
        ///key = &quot;value&quot;  # This is a comment at the end of a line
        ///another = &quot;# This is not a comment&quot;.
        /// </summary>
        internal static string CommentTestInput {
            get {
                return ResourceManager.GetString("CommentTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = &quot;no key name&quot;  # INVALID.
        /// </summary>
        internal static string EmptyKeyNameTestInput {
            get {
                return ResourceManager.GetString("EmptyKeyNameTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first = &quot;Tom&quot; last = &quot;Preston-Werner&quot; # INVALID.
        /// </summary>
        internal static string MultiplePairsOnOneLineTestInput {
            get {
                return ResourceManager.GetString("MultiplePairsOnOneLineTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = &quot;value&quot;
        ///bare_key = &quot;value&quot;
        ///bare-key = &quot;value&quot;
        ///1234 = &quot;value&quot;.
        /// </summary>
        internal static string NonSimpleKeysTestInput {
            get {
                return ResourceManager.GetString("NonSimpleKeysTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;127.0.0.1&quot; = &quot;value&quot;
        ///&quot;character encoding&quot; = &quot;value&quot;
        ///&quot;ʎǝʞ&quot; = &quot;value&quot;
        ///&apos;key2&apos; = &quot;value&quot;
        ///&apos;quoted &quot;value&quot;&apos; = &quot;value&quot;.
        /// </summary>
        internal static string QuotedKeysTestInput {
            get {
                return ResourceManager.GetString("QuotedKeysTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key = # INVALID .
        /// </summary>
        internal static string UnspecifiedValueTestInput {
            get {
                return ResourceManager.GetString("UnspecifiedValueTestInput", resourceCulture);
            }
        }
    }
}
